### ISSUE TITLE
Ability to set "Does this skill contain advertising?" on Compliance Tab

### ISSUE THREAD

**Issue by michaelmyers** [alexa-labs/ask-cli#16]
I think this compliance radio button is relatively new but it would be nice to have a way to set it from the skill schema.

<img width="443" alt="screen shot 2017-06-22 at 1 26 40 pm" src="https://user-images.githubusercontent.com/921356/27447372-ac7ec8f0-574e-11e7-8c96-cc5f29122283.png">

**Comment by RonWang** [comment]
Hey @michaelmyers ,
This feature has now been supported in the skill.json file in the skill-package folder. Please use "containAds" to set this field. Please check [SMAPI Skill Manfest Doc](https://developer.amazon.com/docs/smapi/skill-manifest.html#privacyandcompliance) for more details about this field.

Thanks!
-Ron
