### ISSUE TITLE
more descriptive error message when intent definition refers to nonexistent type

### ISSUE THREAD

**Issue by ashuntwo** [alexa-labs/ask-cli#19]
Hi folks,

I had an intent defined like this: 
    {
        "name": "Promote",
        "slots": [
          {
            "name": "world",
            "type": "World"
          }
        ],
        "samples": [
          "promote {world}"
        ]
      },

In fact, the type should have been "Worlds". The error didn't tell me exactly what was wrong. 

Error code: 400
{ message: 'The model definition is not valid.',
  violations: [ { message: 'model.type.name is unknown slot type name' } ] }

Adding a line number or a specific unknown value would be helpful.

Thanks,

Andy

**Comment by RonWang** [comment]
Hey Andy,

This has been supported now with a specific error code and the value name! I will close this issue then.

Thanks,
-Ron
