### ISSUE TITLE
empty permissions field causes 500 when deployed

### ISSUE THREAD

**Issue by mim-Armand** [alexa-labs/ask-cli#34]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
The error message should point to the problem ( an empty array for the `permissions` field is not a valid value and that the field needs to be removed instead of being empty )

## Current Behavior
500 - Server error

**CLI Snapshot**
<img width="455" alt="Screen Shot 2019-10-17 at 5 24 05 PM" src="https://user-images.githubusercontent.com/1734237/67052192-06a23380-f103-11e9-803d-efdc5e6ae022.png">

## Steps to Reproduce (for bugs)
* Create a new skill using the CLI ( I used the hello world template )
* Edit the `skill.json` manifest file and add the field `permissions` as bellow:
```
...
"privacyAndCompliance": {
...,
permissions: []
}
...
```
* try to deploy the project `ask deploy` ( you'll get a `500 - server error` )

## Possible Solution

I would just handle this error and return an informative/helpful message otherwise it may be a headache to debug!

## Your Environment and Context

* ask-cli version: 1.7.15
* Operating System and version: MAC book pro - Catalina
* Node.js version used for development: 8
* NPM version used for development: 6.9.0

**Comment by RonWang** [comment]
Hey @mim-Armand ,

This issue is coming from our upstream SMAPI service. Could you share more details about your skill.json file, like where do you put the "permissions" field to? Is it inside the "privacyAndCompliance"?

Thanks,
Ron

**Comment by mim-Armand** [comment]
Thanks, @RonWang for the quick response,
I double-checked and I was actually missing the `privacyAndCompliance`, you'll get a **500** if you pass the `"permissions": []` directly under `apis`.

I'll post a minimal manifest that causes server error bellow:
```json
{
  "manifest": {
    "publishingInformation": {
      "locales": {
        "en-US": {
          "name": "test_skill",
          "summary": "Sample Short Description",
          "description": "Sample Full Description",
          "examplePhrases": [
            "Alexa open hello world",
            "hello",
            "help"
          ],
          "keywords": []
        },
        "en-GB": {
          "name": "test_skill",
          "summary": "Sample Short Description",
          "description": "Sample Full Description",
          "examplePhrases": [
            "Alexa open hello world",
            "hello",
            "help"
          ],
          "keywords": []
        }
      },
      "isAvailableWorldwide": true,
      "testingInstructions": "Sample Testing Instructions.",
      "category": "KNOWLEDGE_AND_TRIVIA",
      "distributionCountries": []
    },
    "apis": {
      "custom": {
        "endpoint": {
          "sourceDir": "lambda/custom",
          "uri": "ask-custom-test_skill-default"
        }
      },
      "permissions": []
    },
    "manifestVersion": "1.0"
  }
}
```

**Comment by RonWang** [comment]
Hey @mim-Armand ,
I have forwarded this 500 exception case to our service team to fix the issue. Thank you so much for posting this error case to us!

Best,
Ron

**Comment by RonWang** [comment]
One tip to get rid of this 500 error is to make sure your permissions array is not set as an empty list.  Empty permissions array is the reason to trigger this internal server error.

**Comment by mim-Armand** [comment]
True,
Thanks so much for investigating the issue,
Overall It's good to prevent them 500s! but as you mentioned it's easy and straight forward to avoid this scenario, please feel free to close the issue and thank you again for your time.

Best,
- mim

**Comment by RonWang** [comment]
Close this one as it has been solved in SMAPI service.
