### ISSUE TITLE
Bad Request Failed to refresh access token on uploading skill package

### ISSUE THREAD

**Issue by jbeard4** [alexa-labs/ask-cli#35]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

`askx deploy` should run successfully.

## Current Behavior

Run `askx deploy` produces error message `Bad Request Failed to refresh access token`

**CLI Snapshot**

```
[jacob@localhost warren-alexa-skill-3]$ node ~/.nvm/versions/node/v12.12.0/bin/askx deploy
==================== Deploy Skill Metadata ====================
o Uploading the entire skill package (it may take few minutes to build the skill metadata)...Error: Bad Request
Failed to refresh access token.
```

## Steps to Reproduce (for bugs)

Yesterday, I set up an LWA account, set the environment variables ASK_LWA_CLIENT_ID and ASK_LWA_CLIENT_SECRET, and was able to update my Alexa skill successfully. Today, this no longer works. My hypothesis is that the access token has expired (confirmed by debugging the code, and observing that `isTokenExpired(profile)` returns true), and there is perhaps some bug inside of oauth-wrapper.js or simple-auth2 module which is preventing the oauth token from refreshing successfully. 

## Possible Solution

Unsure. I would appreciate any insight you could share on further steps to debug this.

## Your Environment and Context

* ask-cli version: askx 0.1.1
* Operating System and version: Fedora 29
* Node.js version used for development: v12.12.0
* NPM version used for development: 6.11.3

**Comment by jbeard4** [comment]
This is the HTTP request that fails:

```
{
  method: 'POST',
  uri: 'https://api.amazon.com/auth/o2/token',
  headers: {
    Accept: 'application/json',
    Authorization: 'Basic <hidden>'
  },
  form: {
    grant_type: 'refresh_token',
    refresh_token: <hidden>,
    client_id: 'amzn1.application-oa2-client.0e8c7a04e1f84d6d81d71bc03b5542cc',
    client_secret: <hidden>
  }
}
```

It returns error:

```
{
  name: 'Error',
  status: 400,
  message: 'Bad Request',
  context: {
    error: 'unauthorized_client',
    error_description: 'Not authorized for requested operation'
  }
}
```

**Comment by jbeard4** [comment]
I figured it out. 
I had created a [Login with Amazon](https://login.amazon.com/) client, rather than the through the [developer console](https://developer.amazon.com/loginwithamazon/console/site/lwa/overview.html). I believe this is why the token refresh was failing, as this is mentioned explicitly in the developer documentation for SMAPI [here](https://developer.amazon.com/docs/smapi/smapi-overview.html).

Although, confusingly, the code comments [here](https://github.com/alexa-labs/ask-cli/blob/master/lib/utils/oauth-wrapper.js#L18) provide conflicting instructions. This should probably be considered a documentation bug.

I had to remove my `~/.ask/cli_config` and re-init my ask client and log back into my developer account. Now `askx deploy` seems to be working well again.

**Comment by jbeard4** [comment]
I am changing this from "Bug Report" to "Documentation issue or request"

**Comment by RonWang** [comment]
Thanks for your information, and we have updated the links by the latest commit https://github.com/alexa-labs/ask-cli/commit/00d94b4c45e8072d398374f5c51a282cb151b800. Close this issue accordingly.
