### ISSUE TITLE
Node 8 end of life

### ISSUE THREAD

**Issue by matthewp** [alexa-labs/ask-cli#37]
Hi, I just received an email from AWS about Lambda's Node 8 supporting EOL being at the end of 2019. However the ASK cli generates new projects with Node 8. Does the 2019 EOL not apply to Lambda functions being used by Alexa Skills? If it does apply, is there anything we can do to fix this? Thanks.

**Comment by matthewp** [comment]
No answer in a month, is this project not maintained?  I got another email about this. How are we supposed to create Alexa projects going forward?

**Comment by habuma** [comment]
I'm not a project maintainer, but I may know why you're concerned. ASK CLI does not generate projects for Node 8. When you are given the choice between "Node.js V8" and "Python", the V8 doesn't refer to the version of Node, but rather the name of the Node.js engine in play, which is confusingly named "V8". 

I'll admit that I was confused by this for a moment, too. But although I keep selecting "Node.js V8", I'm deploying skills for Node.js v13.x with no problems.

**Comment by ChihYing7509** [comment]
Sorry for the late reply.
Thank you for your message. As you mentioned, Node 8 will not be supported going forward. 
That is a good suggestion about not defaulting to Node v8.10. We will take it under advisement and keep you updated.

**Comment by ChihYing7509** [comment]
As mentioned above, Nodejs v8.x support has ended starting from 2020.

We have upgraded all the skill templates, changing them from Nodejs v8 to v10.

I have closed this issue. Thanks.

**Comment by matthewp** [comment]
Thank you!
