### ISSUE TITLE
Simple-OAuth2 library update

### ISSUE THREAD

**Issue by jonathansamines** [alexa-labs/ask-cli#49]
Hi, I am the simple-oauth2 library maintainer, and just noticed this project is using simple-oauth2 (which is great!).

However I also noticed you are still using v1 (which is deprecated). I am wondering if there is something stopping you from upgrading to the latest version (v3)? Please let me know if there is something I can help with to support your upgrade.

Thanks!

**Comment by kakhaUrigashvili** [comment]
@jonathansamines I have created a PR: https://github.com/alexa-labs/ask-cli/pull/54

**Comment by RonWang** [comment]
Thanks @kakhaUrigashvili for creating the PR~!

Hi @jonathansamines , our CLI v1 has been using your great library since the release! We cannot update to v3 mainly because our minimum requirement for NodeJS is v6.4. As you may notice in Travis [build #54] (https://travis-ci.org/alexa-labs/ask-cli/builds/645639819?utm_medium=notification&utm_source=github_status) it fails our build.

In addition to the min NodeJS requirement, we'd also want to pass in our http-client to centralize the network control. Do you know if you support custom http-client in simple-oauth2?

**Comment by jonathansamines** [comment]
Hey @RonWang  Great to hear. Unfortunately simple-oauth2 v3 uses some Javascript features only available on Node 8 and above. My understanding is that Node versions below 10 are now unsafe to use because they no longer receive security updates. Is the minimum runtime requirement something you would be willing to change?

With regard of the custom http client, is using a custom library (such as request instead of Wreck) what are you asking about or something different such as being able to provide a custom http agent?

**Comment by RonWang** [comment]
Hi @jonathansamines , for the usage of custom http client, we need the full control over the network activities to support features like better debug and track metrics etc. This could be a really useful feature also applied to your library~! 

For the runtime issue, we actually don't have much option as that's promised to our users for v1 ask-cli. We will definitely consider about it for this ask-cli-x library!

**Comment by jonathansamines** [comment]
@RonWang Got it, just a question. How are you currently taking control over the http client library? I am curious to see how the feature might be designed.

**Comment by RonWang** [comment]
@jonathansamines  Sure no problem.
Here is our metrics tracking through user-agent: https://github.com/alexa-labs/ask-cli/blob/develop/lib/clients/http-client.js#L44. And our --debug HTTP network trace https://github.com/alexa-labs/ask-cli/blob/develop/lib/clients/http-client.js#L98.

IMHO it's up to you to define what's the httpClient interface that a custom provider needs to implement. User only needs to follow the protocol. Feel free to let us know if you want to know more about it! Will close the issue for now~
