### ISSUE TITLE
Missing ask-resources.json error when trying to do askx deploy

### ISSUE THREAD

**Issue by panw** [alexa-labs/ask-cli#52]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

I cloned a sample skill from GitHub, but when I do `askx deploy`, I receive the following error:
```
[Error]: File /Users/itspanw/skill-sample-nodejs-hello-world/ask-resources.json not exists.
```
I should be able to look through the documentation and find instructions on how to add the `ask-resources.json` file if it's missing or the CLI should add it to skills that don't have it.

## Current Behavior

When I do `askx deploy`, I get the error and don't know how to address the issue.

**CLI Snapshot**

## Steps to Reproduce (for bugs)

1. `git clone git@github.com:alexa/skill-sample-nodejs-hello-world.git`
1. `cd skill-sample-nodejs-hello-world.git`
1. `askx deploy`

## Possible Solution

Have the CLI add this file if it's missing from a skill project and/or update documentation with explanation on how to resolve this issue.

## Your Environment and Context

* ask-cli version: 0.6.1
* Operating System and version: MacOS Mojave v 10.14.6
* Node.js version used for development: v11.11.0
* NPM version used for development: 6.13.6

**Comment by kakhaUrigashvili** [comment]
@panw We added a better error message indicating that the command needs to run from the root directory of the project. for example:
`[Error]: CliFileNotFoundError: File /Users/kakuri/AlexaSkills/Helloworld/code/ask-resources.json not exists.
[Warn]: Please make sure you are in the root directory of the project.`
